name: "GHA telemetry info"
description: Returns identifier metadata that is useful in OpenTelemetry
outputs:
  trace_id:
    description: Global ID; one per repo/run combination. Shared among all jobs in the run.
    value: ${{ steps.get-job-info.outputs.trace_id }}
  span_id:
    description: |
      Trace id combined with job name - this is the span that wraps the whole job.
      There will be multiple spans per top-level trace ID.
    value: ${{ steps.get-job-info.outputs.span_id }}
  job_info_json:
    description: Full job info, including steps with their status and start/complete times
    value: ${{ steps.get-job-info.outputs.job_info_json }}
  job_name:
    description: Human-readable identifier for this job (often a description of a matrix step)
    value: ${{ steps.get-job-info.outputs.job_name }}

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: get-job-info
      with:
        retries: 3
        script: |
          const script = require('${{ github.action_path }}/common-js/github-info.js');
          const values = await script({github, context, process});
          core.setOutput("trace_id", values["trace_id"]);
          core.setOutput("job_info_json", values["job_info_json"]);
          core.setOutput("job_name", values["job_name"]);
          core.setOutput("span_id", values["span_id"]);