on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  example_matrix:
    name: ${{ matrix.os}}-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - uses: ./telemetry-setup
        id: telemetry-setup
      - name: Verify that telemetry setup has some data
        run: |
          [[ "${{ steps.telemetry-setup.outputs.trace_id }}" = "" ]] && { echo "trace_id is empty; erroring out" ; exit 1; } || echo "trace_id is ok"
          [[ "${{ steps.telemetry-setup.outputs.job_name }}" != "${{ matrix.os}}-${{ matrix.version }}" ]] && { echo "job_name is not expected value ("${{ matrix.os}}-${{ matrix.version }}"); erroring out" ; exit 1; }  || echo "job_name is ok"
          [[ "${{ steps.telemetry-setup.outputs.span_id }}" = "" ]] && { echo "span_id is empty; erroring out" ; exit 1; } || echo "span_id is ok"
          echo "All expected outputs are in order! Hooray!"