on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  trace_id_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Download gha-tools with git clone
        run: |
            git clone https://github.com/msarahan/gha-tools.git -b add-telemetry-traceparent-scripts /tmp/gha-tools
            echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}"
      - name: test trace id script
        run: |
            echo $(rapids-get-telemetry-traceparent trace_id_test)
      - name: Get job traceparent
        uses: ./telemetry-traceparent
        id: job-traceparent
      - name: Echo value from job
        run: echo "${{steps.job-traceparent.outputs.traceparent}}"
  example_matrix:
    name: ${{ matrix.os}}-${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2]
        os: [ubuntu-latest] # , windows-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Download gha-tools with git clone
        run: |
            git clone https://github.com/msarahan/gha-tools.git -b add-telemetry-traceparent-scripts /tmp/gha-tools
            echo "/tmp/gha-tools/tools" >> "${GITHUB_PATH}"
      # Run job with traceparent. We'll validate that this matches in the summary data.
      - name: Get job traceparent
        uses: ./telemetry-traceparent
        id: job-traceparent
      - name: Generate traceparent for a step
        uses: ./telemetry-traceparent
        id: step-traceparent
        with:
            # Have to set this manually, seemingly. No way to introspect the step name or id from here.
            step_name: "Download gha-tools with git clone"
      - name: Echo computed step traceparent
        run: |
            echo "GHA tools clone job traceparent: ${{ steps.step-traceparent.outputs.traceparent }}"
      - name: Test OTel export of job JSON
        uses: ./telemetry-summarize
        with:
            endpoint: "https://localhost:4318"
            traceparent: ${{ steps.job-traceparent.outputs.traceparent}}
